### ISSUE TITLE
models: new DB table to hold workspace file retention rules

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-db#172]
Design a new DB table for keeping retention rules following RFC https://github.com/reanahub/reana-client/issues/610

Example:

| workflow_id (FK) | workspace_files     | retention_days  | apply_on            |
| ---------------- | ------------------- | --------------- | ------------------- |
| 1111-2232-3333   | myfetched/**/*.root | 1               | NULL                |
| 1111-2232-3333   | myfiltered/*.root   | 7               | NULL                |
| 1111-2232-3333   | myfits/             | 30              | NULL                |
| 1111-2232-3333   | myplots/*.eps       | 365             | NULL                |
| 1111-2232-3333   | myplots/*.png       | 365             | 2023-05-02 00:00:01 |

This table will be populated by parsing `workspace.retention_days` from `reana.yaml` when the workflow is created.

(Side-comment: and, in case a user reruns a workflow, they may modify `reana.yaml` as well, so please beware that these entries can change after DB rows are created. IOW we need both nice CREATE and nice UPDATE methods to manipulate this table for a given workflow.)

This table will then be used by the nightly workspace retention rule applier daemon that will read the rows, and, depending on the workflow status, process some of them (and delete the files), and skip some of them (until their time will come).

Note that the `apply_on` date time column is illustrating one way how we could avoid processing too many rows unnecessarily every night. The defalut value is NULL, meaning the row was not processed yet. Example: the workflow run 1111-2222-3333 finishes on May 1st. The daemon will first process this workflow run on May 2nd. It will go through each rule and set `apply_on` date time stamp appropriately, e.g. for `myplots/*.png` it will be set to `2023-05-02 00:00:01`. And when the daemon will run the next day on May 3rd, it won't need to touch only those rows `WHERE NOW() > apply_on`, so to speak.

The details on the daemon's work will be part of another ticket, but it is good to think about these usage scenarios whilst designing the DB model table in order to avoid doing many DB model changes later.

The expected outcome if this issue therefore is:

- think about a DB workspace file retention rule storage table and either confirm the above high-level design or propose an alternative;
- create a new DB model table (with efficient indexes since it may grow a lot);
- define nice methods to insert (by workflow submitter) and update (by both workflow update by user or by the future retention rule processing daemon);
- create new DB alembic upgrade recipe.

**Comment by VMois** [comment]
In addition, it would be good to populate our REANA dev wiki with a page on how to work with Alembic.

**Comment by tiborsimko** [comment]
Update: if we use the same table to both store the rules and the output of the nightly daemon, then we would probably need another column such as `applied_on` with value NULL and where we store time stamp _after_ daemon deleted the files.  So that we won't need to process in the future again and again.

(Though we risk a situation where people would upload into their old workspace some new files after retention period finished, e.g. for debugging purposes, and then they wouldn't run `restart`, so the workspace would never be cleaned again.  We could have some monthly or yearly daemon checkup runs to catch these, basically to verify whether the rules were well applied as claimed.)

**Comment by mdonadoni** [comment]
I think the table layout is good! I just have a few comments/questions.

> (Side-comment: and, in case a user reruns a workflow, they may modify `reana.yaml` as well, so please beware that these entries can change after DB rows are created. IOW we need both nice CREATE and nice UPDATE methods to manipulate this table for a given workflow.)

We have to be careful when handling this case. If a user restarts a workflow, the new run will have a different id (see [here](https://github.com/reanahub/reana-server/blob/b666bfa0edbf18bc6bf26e0dd63c82e89c76aa1f/reana_server/utils.py#L563)).  However, it will reuse the same workspace as before (as you can see [here](https://github.com/reanahub/reana-server/blob/b666bfa0edbf18bc6bf26e0dd63c82e89c76aa1f/reana_server/utils.py#L569)). This means that, if we simply consider each restarted workflow as an independent workflow, it might happen that files are removed even while another run is being executed.

One possible option would be to process retention rules only for the last restart of each workflow. However, it might still happen that files are removed before the user requests a new restart.

Do you have any other ideas or suggestions?

> Note that the `apply_on` date time column is illustrating one way how we could avoid processing too many rows unnecessarily every night. The defalut value is NULL, meaning the row was not processed yet. Example: the workflow run 1111-2222-3333 finishes on May 1st. The daemon will first process this workflow run on May 2nd. It will go through each rule and set `apply_on` date time stamp appropriately, e.g. for `myplots/*.png` it will be set to `2023-05-02 00:00:01`. And when the daemon will run the next day on May 3rd, it won't need to touch only those rows `WHERE NOW() > apply_on`, so to speak.

I guess we can also set `apply_on` when the workflow finishes its execution (either failing or not).

> Update: if we use the same table to both store the rules and the output of the nightly daemon, then we would probably need another column such as applied_on with value NULL and where we store time stamp after daemon deleted the files. So that we won't need to process in the future again and again.

Do we want to store some other details, for example which files where deleted?

We can also consider moving the already processed rules in another table, if we want to keep the table with the rules yet to be processed as small as possible.

**Comment by VMois** [comment]
> One possible option would be to process retention rules only for the last restart of each workflow. 

I think this is a good way. In case of restarts, the daemon can work like that, in general:

0. Every 24 hours.

1. Check if the workflow had new restarts from last time, and update rules if needed based on the finish time of the **latest** restart.

2. Check if rules (whether updated or not) should be applied now (the latest workflow restart is not running, etc.)

3. If rules need to be applied, delete files.

But, if someone waits for a longer time and we clean the files, they might have problems with restarting. Although, if we keep inputs untouched, restarting the workflow will always be possible.
