### ISSUE TITLE
Addition of audit table.

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-db#18]
Actions like deletion of a workflow and others, could be logged in a more complete way if there would be a table to store meta information about them.
This could be an `audit` table with the following structure:
```
  audit
----------
creation_timestamp
last_modification_timestamp
user (id)
action (text)
details (json)

```

In the workflow deletion case a row would show:
who (user) 
did (deleted in action)
what (workflow id in json)
and how (hard/soft delete details in json).

Other actions like file uploads, downloads, removals could be captured in a similar way.

**Comment by mvidalgarcia** [comment]
Shouldn't the `action` be an enum? Otherwise, querying the multiple actins can get messy.

**Comment by tiborsimko** [comment]
Enum may be hard to understand without the Python context... A short unique six-character string or something like that might be enough.  Something like:

AuditLog:

| column | example | note |
| -----------|------|------|
| uuid       | (autogenerated id)   | *primary key* |
| action_user |  John Doe | *can be obviously user ID foreign key referencing the user table* |
| action_name |  tokenrequest | *taken from well-defined list of all actions* |
| action_time |  YYYY-MM-DD hh:mm:ss | *usual timestamp when the action happened* |
| action_args |  {'something': 42, 'comment': 'please can I have a token fast?'} | *any further details we may want to keep and search for; can be different for each action, so JSON column value probably* |


Just some quick thoughts, we can muse longer about the best AuditLog table structure and we can get inspiration by reviewing some existing Python and non-Python audit trail packages.
