### ISSUE TITLE
installation: missing subpackages in production build

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-db#77]
Our `setup.py` configuration [doesn't dynamically discover new subpackages](https://github.com/reanahub/reana-db/blob/ce07a07ec6f5bb667fb20ee66aca48fa68f61836/setup.py#L67). We should [use `find_packages()`](https://github.com/reanahub/reana-db/blob/ce07a07ec6f5bb667fb20ee66aca48fa68f61836/setup.py#L50) so subpackages are included in the production build.
```console
$ pip show reana-db
Name: reana-db
Version: 0.7.0a2
Summary: REANA-DB.
Home-page: https://github.com/reanahub/reana-db
Author: REANA
Author-email: info@reana.io
License: UNKNOWN
Location: /Users/rodrigdi/.virtualenvs/test/lib/python3.6/site-packages
Requires: psycopg2-binary, alembic, reana-commons, SQLAlchemy, sqlalchemy-utils, cryptography
Required-by: 
$ ls /Users/rodrigdi/.virtualenvs/test/lib/python3.6/site-packages/reana_db
__init__.py cli.py      database.py utils.py
__pycache__ config.py   models.py   version.py
```
_`alembic`, a subpackage present in master, is not shipped with the current production builds._

**Comment by tiborsimko** [comment]
> License: UNKNOWN

A side comment: why is the license field UNKNOWN? We do declare proper classifiers; we could look into fixing this as well.
