### ISSUE TITLE
models: prepare DB schema to hold quota usage

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-db#83]
Enrich models to hold quota usage information for HDD and CPU usage.

1. Research how this is being done in other systems:
    - Quotas in HTCondor see [here](https://research.cs.wisc.edu/htcondor/manual/v7.6/condor_userlog.html)
    - Quotas in Kubernets see [here](https://kubernetes.io/docs/concepts/policy/resource-quotas/)
    - Quotas in Slurm see [here](https://slurm.schedmd.com/sreport.html)

      Note: the sense of quota might vary between backends, for instance, in HTCondor it is what the job actually consumed, however for Kubernetes it is the limit the job can reach.

2. Extend models (probably create a new accounting table)
    - MVP workflows and sessions/notebooks, nice to have for jobs.

      Note: Focus on adding every field we can potentially fill, even if we do not fill them in the first version of user quotas implementation (to minimize DB models changes).

**Comment by diegodelemos** [comment]
For the MVP we won't make differences in resource types e.g. node type expensive/cheap, CPU type expensive/cheap etc...

**Comment by tiborsimko** [comment]
To avoid DB model changes, let's not hard code any resource type (cpu, disk) so that we can add easily new (e.g. number_of_workflows, number_of_sessions, or whatnot).

The DB tables could have a free text field for these values, and we can handle proper resources type referencing etc in the application (probably in `r-commons`).

If we go for a flat design, this will allow to account for type too, e.g. `disk_s3`, `disk_eos`, `disk_tape` or something.

**Comment by tiborsimko** [comment]
Results of DB model brainstorming: the new tables could look as follows:

```
user
----
id
email
etc

resource
--------
id
type (cpu, disk OR cpu_workflows, cpu_notebooks)
name (cpu_kubernetes, cpu_htcondor, cpu_slurm, gpu, gpu_very_expensive)
unit ("KiB" for disk, "minutes" for cpu)
title ("Special GPU cluster")

user_resource
-------------
id_user
id_resource
quota_limit (set by admins)
quota_used  (could be calculated from w_r, but beware of disk removal etc)
last_updated

(... and also enrich AuditLog with entries about who/when set limits,
e.g. john had 10 TB but later reduced to 5 TB and later increased to
25 TB, just for housekeeping purposes)

workflow_resource
-----------------
id_workflow
id_resource
quantity_used
timestamp

(... and put also to audit log to have historical point of view)

(... or do not use at all? if the info in workflow.run_finished etc is properly set even for failed workflow etc, then use that table?)

(... leave a possibility of future outlook of having similar table for jobs?

workflow
--------
interactive_session_*   -> need to split apart into new session table

session_resource
----------------
(... similar as for workflows, with perhaps special notebook treatment, how long notebook is open vs jobs it submits in the future)

job_resource
------------
(... could be used in the future should we start to measure cpu/disk quotas for jobs, not only for workflows, after MVP phase)
```

The precise format to be seen as we proceed with the implementation.
