### ISSUE TITLE
models: disk usage to be stored not calculated everytime

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-db#88]
`get_user_disk_usage` should follow the same approach as `get_user_cpu_usage`, just reading the value from DB and calculate it only if it hasn't been calculated before. The field value should be calculated when:
- Workflow status changes (`workflow_status_change_listener`)
- When https://github.com/reanahub/reana-workflow-controller/issues/333 is executed.

_Originally posted by @diegodelemos in https://github.com/reanahub/reana-db/pull/87#discussion_r497523567_

**Comment by mvidalgarcia** [comment]
When implementing this, https://github.com/reanahub/reana-server/pull/290/commits/fe9ce08922f2daa78d4c2b3254c5bede6d5d3076 should be reverted.
